# Generated by Django 3.2.3 on 2023-09-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0003_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='emp',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
