# Generated by Django 3.2.3 on 2023-09-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0004_auto_20230902_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='emp',
            name='department',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='emp',
            name='phone',
            field=models.BigIntegerField(blank=True),
        ),
    ]
